/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  AdminAssistant,
  AdminAssistantsPostRequest,
} from '../models/index';
import {
    AdminAssistantFromJSON,
    AdminAssistantToJSON,
    AdminAssistantsPostRequestFromJSON,
    AdminAssistantsPostRequestToJSON,
} from '../models/index';

export interface AdminAssistantsPostOperationRequest {
    adminAssistantsPostRequest?: AdminAssistantsPostRequest;
}

/**
 * AdminApi - interface
 * 
 * @export
 * @interface AdminApiInterface
 */
export interface AdminApiInterface {
    /**
     * 
     * @summary List assistants
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    adminAssistantsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminAssistant>>>;

    /**
     * 
     * List assistants
     */
    adminAssistantsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminAssistant>>;

    /**
     * 
     * @summary Create assistant
     * @param {AdminAssistantsPostRequest} [adminAssistantsPostRequest] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof AdminApiInterface
     */
    adminAssistantsPostRaw(requestParameters: AdminAssistantsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminAssistant>>;

    /**
     * 
     * Create assistant
     */
    adminAssistantsPost(requestParameters: AdminAssistantsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminAssistant>;

}

/**
 * 
 */
export class AdminApi extends runtime.BaseAPI implements AdminApiInterface {

    /**
     * 
     * List assistants
     */
    async adminAssistantsGetRaw(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<Array<AdminAssistant>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/admin/assistants`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(AdminAssistantFromJSON));
    }

    /**
     * 
     * List assistants
     */
    async adminAssistantsGet(initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<Array<AdminAssistant>> {
        const response = await this.adminAssistantsGetRaw(initOverrides);
        return await response.value();
    }

    /**
     * 
     * Create assistant
     */
    async adminAssistantsPostRaw(requestParameters: AdminAssistantsPostOperationRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<AdminAssistant>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        const response = await this.request({
            path: `/admin/assistants`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: AdminAssistantsPostRequestToJSON(requestParameters.adminAssistantsPostRequest),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => AdminAssistantFromJSON(jsonValue));
    }

    /**
     * 
     * Create assistant
     */
    async adminAssistantsPost(requestParameters: AdminAssistantsPostOperationRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<AdminAssistant> {
        const response = await this.adminAssistantsPostRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
