/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import type {
  WordEntry,
} from '../models/index';
import {
    WordEntryFromJSON,
    WordEntryToJSON,
} from '../models/index';

export interface DictionaryWordGetRequest {
    word?: string;
}

/**
 * DictionaryApi - interface
 * 
 * @export
 * @interface DictionaryApiInterface
 */
export interface DictionaryApiInterface {
    /**
     * 
     * @summary Get word
     * @param {string} [word] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof DictionaryApiInterface
     */
    dictionaryWordGetRaw(requestParameters: DictionaryWordGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WordEntry>>;

    /**
     * 
     * Get word
     */
    dictionaryWordGet(requestParameters: DictionaryWordGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WordEntry>;

}

/**
 * 
 */
export class DictionaryApi extends runtime.BaseAPI implements DictionaryApiInterface {

    /**
     * 
     * Get word
     */
    async dictionaryWordGetRaw(requestParameters: DictionaryWordGetRequest, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<runtime.ApiResponse<WordEntry>> {
        const queryParameters: any = {};

        if (requestParameters.word !== undefined) {
            queryParameters['word'] = requestParameters.word;
        }

        const headerParameters: runtime.HTTPHeaders = {};

        const response = await this.request({
            path: `/dictionary/word`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => WordEntryFromJSON(jsonValue));
    }

    /**
     * 
     * Get word
     */
    async dictionaryWordGet(requestParameters: DictionaryWordGetRequest = {}, initOverrides?: RequestInit | runtime.InitOverrideFunction): Promise<WordEntry> {
        const response = await this.dictionaryWordGetRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
