/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ClientAssistant
 */
export interface ClientAssistant {
    /**
     * 
     * @type {number}
     * @memberof ClientAssistant
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof ClientAssistant
     */
    name: string;
}

/**
 * Check if a given object implements the ClientAssistant interface.
 */
export function instanceOfClientAssistant(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "name" in value;

    return isInstance;
}

export function ClientAssistantFromJSON(json: any): ClientAssistant {
    return ClientAssistantFromJSONTyped(json, false);
}

export function ClientAssistantFromJSONTyped(json: any, ignoreDiscriminator: boolean): ClientAssistant {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'name': json['name'],
    };
}

export function ClientAssistantToJSON(value?: ClientAssistant | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'name': value.name,
    };
}

