/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface Conversation
 */
export interface Conversation {
    /**
     * 
     * @type {number}
     * @memberof Conversation
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    provider: string;
    /**
     * 
     * @type {number}
     * @memberof Conversation
     */
    assistantId: number;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof Conversation
     */
    metadata?: string;
}

/**
 * Check if a given object implements the Conversation interface.
 */
export function instanceOfConversation(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "id" in value;
    isInstance = isInstance && "provider" in value;
    isInstance = isInstance && "assistantId" in value;

    return isInstance;
}

export function ConversationFromJSON(json: any): Conversation {
    return ConversationFromJSONTyped(json, false);
}

export function ConversationFromJSONTyped(json: any, ignoreDiscriminator: boolean): Conversation {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'provider': json['provider'],
        'assistantId': json['assistantId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'metadata': !exists(json, 'metadata') ? undefined : json['metadata'],
    };
}

export function ConversationToJSON(value?: Conversation | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'provider': value.provider,
        'assistantId': value.assistantId,
        'name': value.name,
        'metadata': value.metadata,
    };
}

