/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ConversationsPostRequest
 */
export interface ConversationsPostRequest {
    /**
     * 
     * @type {number}
     * @memberof ConversationsPostRequest
     */
    assistantId: number;
}

/**
 * Check if a given object implements the ConversationsPostRequest interface.
 */
export function instanceOfConversationsPostRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "assistantId" in value;

    return isInstance;
}

export function ConversationsPostRequestFromJSON(json: any): ConversationsPostRequest {
    return ConversationsPostRequestFromJSONTyped(json, false);
}

export function ConversationsPostRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): ConversationsPostRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'assistantId': json['assistantId'],
    };
}

export function ConversationsPostRequestToJSON(value?: ConversationsPostRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'assistantId': value.assistantId,
    };
}

