/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { StudyList } from './StudyList';
import {
    StudyListFromJSON,
    StudyListFromJSONTyped,
    StudyListToJSON,
} from './StudyList';

/**
 * 
 * @export
 * @interface StudylistsGet200Response
 */
export interface StudylistsGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StudylistsGet200Response
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<StudyList>}
     * @memberof StudylistsGet200Response
     */
    data: Array<StudyList>;
    /**
     * 
     * @type {string}
     * @memberof StudylistsGet200Response
     */
    cursor: string;
}

/**
 * Check if a given object implements the StudylistsGet200Response interface.
 */
export function instanceOfStudylistsGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasMore" in value;
    isInstance = isInstance && "data" in value;
    isInstance = isInstance && "cursor" in value;

    return isInstance;
}

export function StudylistsGet200ResponseFromJSON(json: any): StudylistsGet200Response {
    return StudylistsGet200ResponseFromJSONTyped(json, false);
}

export function StudylistsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudylistsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasMore': json['hasMore'],
        'data': ((json['data'] as Array<any>).map(StudyListFromJSON)),
        'cursor': json['cursor'],
    };
}

export function StudylistsGet200ResponseToJSON(value?: StudylistsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasMore': value.hasMore,
        'data': ((value.data as Array<any>).map(StudyListToJSON)),
        'cursor': value.cursor,
    };
}

