/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WordInStudyList } from './WordInStudyList';
import {
    WordInStudyListFromJSON,
    WordInStudyListFromJSONTyped,
    WordInStudyListToJSON,
} from './WordInStudyList';

/**
 * 
 * @export
 * @interface StudylistsIdWordsGet200Response
 */
export interface StudylistsIdWordsGet200Response {
    /**
     * 
     * @type {boolean}
     * @memberof StudylistsIdWordsGet200Response
     */
    hasMore: boolean;
    /**
     * 
     * @type {Array<WordInStudyList>}
     * @memberof StudylistsIdWordsGet200Response
     */
    data: Array<WordInStudyList>;
    /**
     * 
     * @type {string}
     * @memberof StudylistsIdWordsGet200Response
     */
    cursor?: string;
}

/**
 * Check if a given object implements the StudylistsIdWordsGet200Response interface.
 */
export function instanceOfStudylistsIdWordsGet200Response(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "hasMore" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function StudylistsIdWordsGet200ResponseFromJSON(json: any): StudylistsIdWordsGet200Response {
    return StudylistsIdWordsGet200ResponseFromJSONTyped(json, false);
}

export function StudylistsIdWordsGet200ResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudylistsIdWordsGet200Response {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'hasMore': json['hasMore'],
        'data': ((json['data'] as Array<any>).map(WordInStudyListFromJSON)),
        'cursor': !exists(json, 'cursor') ? undefined : json['cursor'],
    };
}

export function StudylistsIdWordsGet200ResponseToJSON(value?: StudylistsIdWordsGet200Response | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'hasMore': value.hasMore,
        'data': ((value.data as Array<any>).map(WordInStudyListToJSON)),
        'cursor': value.cursor,
    };
}

