/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface StudylistsGet200ResponseDataInner
 */
export interface StudylistsGet200ResponseDataInner {
    /**
     * 
     * @type {string}
     * @memberof StudylistsGet200ResponseDataInner
     */
    id?: string;
    /**
     * 
     * @type {string}
     * @memberof StudylistsGet200ResponseDataInner
     */
    userId?: string;
    /**
     * 
     * @type {string}
     * @memberof StudylistsGet200ResponseDataInner
     */
    name?: string;
    /**
     * 
     * @type {string}
     * @memberof StudylistsGet200ResponseDataInner
     */
    createdAt?: string;
    /**
     * 
     * @type {string}
     * @memberof StudylistsGet200ResponseDataInner
     */
    updatedAt?: string;
}

/**
 * Check if a given object implements the StudylistsGet200ResponseDataInner interface.
 */
export function instanceOfStudylistsGet200ResponseDataInner(value: object): boolean {
    let isInstance = true;

    return isInstance;
}

export function StudylistsGet200ResponseDataInnerFromJSON(json: any): StudylistsGet200ResponseDataInner {
    return StudylistsGet200ResponseDataInnerFromJSONTyped(json, false);
}

export function StudylistsGet200ResponseDataInnerFromJSONTyped(json: any, ignoreDiscriminator: boolean): StudylistsGet200ResponseDataInner {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': !exists(json, 'id') ? undefined : json['id'],
        'userId': !exists(json, 'userId') ? undefined : json['userId'],
        'name': !exists(json, 'name') ? undefined : json['name'],
        'createdAt': !exists(json, 'createdAt') ? undefined : json['createdAt'],
        'updatedAt': !exists(json, 'updatedAt') ? undefined : json['updatedAt'],
    };
}

export function StudylistsGet200ResponseDataInnerToJSON(value?: StudylistsGet200ResponseDataInner | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'userId': value.userId,
        'name': value.name,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
    };
}

