/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WordDefinition
 */
export interface WordDefinition {
    /**
     * 
     * @type {string}
     * @memberof WordDefinition
     */
    part: string;
    /**
     * 
     * @type {Array<string>}
     * @memberof WordDefinition
     */
    definitions: Array<string>;
}

/**
 * Check if a given object implements the WordDefinition interface.
 */
export function instanceOfWordDefinition(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "part" in value;
    isInstance = isInstance && "definitions" in value;

    return isInstance;
}

export function WordDefinitionFromJSON(json: any): WordDefinition {
    return WordDefinitionFromJSONTyped(json, false);
}

export function WordDefinitionFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordDefinition {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'part': json['part'],
        'definitions': json['definitions'],
    };
}

export function WordDefinitionToJSON(value?: WordDefinition | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'part': value.part,
        'definitions': value.definitions,
    };
}

