/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { WordEntry } from './WordEntry';
import {
    WordEntryFromJSON,
    WordEntryFromJSONTyped,
    WordEntryToJSON,
} from './WordEntry';

/**
 * 
 * @export
 * @interface WordInStudyList
 */
export interface WordInStudyList {
    /**
     * 
     * @type {string}
     * @memberof WordInStudyList
     */
    word: string;
    /**
     * 
     * @type {string}
     * @memberof WordInStudyList
     */
    createdAt: string;
    /**
     * 
     * @type {string}
     * @memberof WordInStudyList
     */
    updatedAt: string;
    /**
     * 
     * @type {WordEntry}
     * @memberof WordInStudyList
     */
    wordEntry?: WordEntry;
}

/**
 * Check if a given object implements the WordInStudyList interface.
 */
export function instanceOfWordInStudyList(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "word" in value;
    isInstance = isInstance && "createdAt" in value;
    isInstance = isInstance && "updatedAt" in value;

    return isInstance;
}

export function WordInStudyListFromJSON(json: any): WordInStudyList {
    return WordInStudyListFromJSONTyped(json, false);
}

export function WordInStudyListFromJSONTyped(json: any, ignoreDiscriminator: boolean): WordInStudyList {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'word': json['word'],
        'createdAt': json['createdAt'],
        'updatedAt': json['updatedAt'],
        'wordEntry': !exists(json, 'wordEntry') ? undefined : WordEntryFromJSON(json['wordEntry']),
    };
}

export function WordInStudyListToJSON(value?: WordInStudyList | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'word': value.word,
        'createdAt': value.createdAt,
        'updatedAt': value.updatedAt,
        'wordEntry': WordEntryToJSON(value.wordEntry),
    };
}

