/* tslint:disable */
/* eslint-disable */
/**
 * English Teacher
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface WsResponse
 */
export interface WsResponse {
    /**
     * 
     * @type {string}
     * @memberof WsResponse
     */
    event: string;
    /**
     * 
     * @type {string}
     * @memberof WsResponse
     */
    data: string;
}

/**
 * Check if a given object implements the WsResponse interface.
 */
export function instanceOfWsResponse(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "event" in value;
    isInstance = isInstance && "data" in value;

    return isInstance;
}

export function WsResponseFromJSON(json: any): WsResponse {
    return WsResponseFromJSONTyped(json, false);
}

export function WsResponseFromJSONTyped(json: any, ignoreDiscriminator: boolean): WsResponse {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'event': json['event'],
        'data': json['data'],
    };
}

export function WsResponseToJSON(value?: WsResponse | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'event': value.event,
        'data': value.data,
    };
}

